# This is a vaild configuration example of Tairitsuru.
# EDIT BEFORE USE! See `tairitsuru_conf.example.toml`.

[transcoding]
enable = false
formart = "mp4"


[storage]
type = "local"

[storage.local]
path = "./data" 


[proxy]
enable = true
type = "http"
bili_api_only = true 

[proxy.http]
addr = "127.0.0.1"
port = 8118


[push]
[push.message]
livestart = """Your favorite uploader {uploader} starts livestreaming! \
               Go to {live_url} and watch now!"""
liveend = """The uploader {uploader} has ended his livestream. \
             He/She has livestreamed for {live_duration}."""
newvideo = """
Your favorite uploader {uploader} uploaded a new video at {datetime}! \n\
Title: {title} \n\
Description: \n\
{description} \n\
Go to {link_bvid} and watch now!
"""

[[push.templates]]
id = "mirai"
type = "mirai"
apiroot = "http://127.0.0.1:8000"
auth = "************"
users = ["123456789", "987654321"]
groups = ["123456789", "987654321"]

[[push.templates]]
id = "tg"
type = "tg"
addr = "https://api.telegram.org/"
auth = "************"
users = ["123456789", "987654321"]


[[watchers]]
nickname = "Tix"
interval = 60

[watchers.video]
uid = 3234445
notify = true

[watchers.live]
roomid = 22114797
notify = true
record = true

# Add more below! And delete this line if you want :)